// ============================================
// Type Utilities Index
// ============================================

// Core types
export type {
  DeepPartial,
  DeepRequired,
  DeepReadonly,
  PickDeep,
  OmitDeep,
  Merge,
  UnionToIntersection,
  LastInUnion,
  FirstInUnion,
  ExcludeNever,
} from './core';

// String types
export type {
  CamelCase,
  KebabCase,
  SnakeCase,
  PascalCase,
  Trim,
  WordCount,
  Brand,
  StringEnum,
  RequiredBy,
  ReadonlyBy,
  OptionalBy,
} from './string';

// Advanced string types
export type {
  Uncapitalize,
  CapitalizeWords,
  TitleCase,
  ScreamingSnakeCase,
  Split,
  Join,
  FileExtension,
  Basename,
  Dirname,
  StartsWith,
  EndsWith,
  RemovePrefix,
  RemoveSuffix,
  Reverse,
  PadLeft,
  PadRight,
} from './advanced-string';

// Advanced object types
export type {
  DeepMerge,
  DeepOmit,
  DeepPick,
  DistributiveOmit,
  DistributivePick,
  Writable,
  DeepWritable,
  NonNullableProperties,
  FunctionParams,
  ObjectParams,
  PickKeys,
  Exact,
  MarkOptional,
  MarkRequired,
  OwnProperties,
  ValueOf,
  KeysOf,
  EntryOf,
  NumericKeysOf,
  StringKeysOf,
  KeysOfType,
  OptionalKeysOf,
  RequiredKeysOf,
  ReadonlyKeysOf,
  WritableKeysOf,
  ObjectLength,
  HasKey,
  Update,
  RequiredAll,
} from './advanced-object';

// Advanced function types
export type {
  AnyFunction,
  AsyncFunction,
  Noop,
  AsyncNoop,
  Predicate,
  Unary,
  Binary,
  Variadic,
  Curried,
  Compose,
  Pipe,
  DebounceFunction,
  ThrottleFunction,
  EventHandler,
  AsyncEventHandler,
  Callback,
  HoF,
  AsyncWrapper,
  SideEffect,
  Silent,
  Memoized,
  Constructor,
  Instance,
  ConstructorParams,
  ThisType,
  OmitThisParameter,
  ThisParameterType,
  BoundThis,
  PartialParameters,
  PartialParametersAtLeast,
  FirstParameter,
  LastParameter,
  NoParameters,
  ObjectParameters,
  PositionalParameters,
  AsyncReturnType,
  SyncReturnType,
} from './advanced-function';

// Pattern utility types (React/Redux inspired patterns)
export type {
  SetState,
  GetState,
  Reducer,
  ReducerState,
  ReducerAction,
  Dispatch,
  DispatchWithGetState,
  RefCallback,
  MutableRef,
  ReadonlyRef,
  Effect,
  Deps,
  EqualityFn,
  HOC,
  RenderFn,
  Slots,
  Result,
  AsyncResult,
  Loading,
  Action,
  Thunk,
  EffectPattern,
  QueueItem,
  CacheEntry,
  Subscription,
  Observer,
  Observable,
  Listener,
  Emitter,
  Factory,
  Builder,
  Adapter,
  Mapper,
  Validator,
  Parser,
  Serializer,
  Repository,
  Service,
  Controller,
  Middleware,
  MemoizedFn,
  Debounced,
  Throttled,
  EventHandlerFn,
  Bound,
  PartialLeft,
  PartialRight,
  FunctionalUpdate,
  Try,
  Either,
  Maybe,
  Optional,
  Nullable,
  AsyncIterableResult,
  IterableResult,
  Stream,
  Command,
  Strategy,
  StateMachine,
  Decorator,
  ProxyHandler,
  Mixin,
  Plugin,
  Extension,
  FeatureFlag,
  Config,
  Logger,
  Metrics,
} from './react';
